### ISSUE TITLE
File path for I2C.h should be <hal/I2C.h

### ISSUE THREAD

**Issue by willtoth** [REVrobotics/2m-Distance-Sensor#7]
As part of the porting for 2020, please change the include file path for I2C.h. It should be <hal/I2C.h> rather than <HAL/I2C.h>. I am able to compile things using the library successfully on Windows (case-insensitive filenames) but not on linux.

```
In file included from /home/hauser/sciborgs-2020/robot-2020/robot/src/subsystems/the_robot/trenchController.h:49:0,
                 from /home/hauser/sciborgs-2020/robot-2020/robot/src/subsystems/the_robot/TheRobotSetup.cpp:32:
/home/hauser/.gradle/caches/transforms-2/files-2.1/deb540110fe5084595fa2d5c06e4659b/DistanceSensor-cpp-0.0.6-headers/rev/Rev2mDistanceSensor.h:38:10: fatal error: HAL/I2C.h: No such file or directory
 #include <HAL/I2C.h>
          ^~~~~~~~~~~
compilation terminated.
```
Having a working vendordep.json for 2020 for this library and having it work on linux would greatly simplify our development and continuous integration tooling. Thanks.

_Originally posted by @chauser in https://github.com/REVrobotics/2m-Distance-Sensor/issues/6#issuecomment-575943002_

**Comment by chauser** [comment]
Hi William,
Thanks for fixing this. I notice that you changed the path for <hal/HAL.h>
to <hal/hal.h>. Unfortunately, the file name in wpilib really is HAL.h. It
is not consistent -- the directory name is lower case but the file name is
upper case.
-- Carl

**Comment by willtoth** [comment]
So it is, thanks for catching! Probably would have seen once it gets built for 2020
